name       : zopfli
version    : 1.0.1
release    : 3
source     :
    - https://github.com/google/zopfli/archive/zopfli-1.0.1.tar.gz : 29743d727a4e0ecd1b93e0bf89476ceeb662e809ab2e6ab007a0b0344800e9b4
license    : Apache-2.0
summary    : Zopfli Compression Algorithm is a compression library.
# Note: This is in programming.library for the upcoming library part ...
description: |
    Zopfli Compression Algorithm is a compression library programmed in C to perform very good, but slow, deflate or zlib compression.
build      : |
    %make
install    : |
    mkdir -p %installroot%/usr/bin
    install -m 00755 zopfli %installroot%/usr/bin/
