name       : zopfli
version    : 1.0.2
release    : 4
source     :
    - https://github.com/google/zopfli/archive/zopfli-1.0.2.tar.gz : 4a570307c37172d894ec4ef93b6e8e3aacc401e78cbcc51cf85b212dbc379a55
license    : Apache-2.0
component  : programming.library
summary    : Zopfli Compression Algorithm is a compression library.
description: |
    Zopfli Compression Algorithm is a compression library programmed in C to perform very good, but slow, deflate or zlib compression.
build      : |
    %make
install    : |
    mkdir -p %installroot%/usr/bin
    install -m 00755 zopfli %installroot%/usr/bin/
