name       : zopfli
version    : 1.0.3
release    : 5
source     :
    - https://github.com/google/zopfli/archive/zopfli-1.0.3.tar.gz : e955a7739f71af37ef3349c4fa141c648e8775bceb2195be07e86f8e638814bd
license    : Apache-2.0
component  : programming.library
summary    : Zopfli Compression Algorithm is a compression library.
description: |
    Zopfli Compression Algorithm is a compression library programmed in C to perform very good, but slow, deflate or zlib compression.
setup      : |
    %cmake -DZOPFLI_BUILD_SHARED=ON
build      : |
    %make
install    : |
    %make_install
