name       : zopfli
version    : 1.0
release    : 2
source     :
    - https://github.com/google/zopfli/archive/zopfli-1.0.0.tar.gz : 386bd801e99bd95f292e7c39fa6a945e4bf1ffec57e16a99024d766fdafb6f96
license    : Apache-2.0
summary    : Zopfli Compression Algorithm is a compression library.
# Note: This is in programming.library for the upcoming library part ...
description: |
    Zopfli Compression Algorithm is a compression library programmed in C to perform very good, but slow, deflate or zlib compression.
build      : |
    %make
install    : |
    mkdir -p %installroot%/usr/bin
    install -m 00755 zopfli %installroot%/usr/bin/
